### ISSUE TITLE
Simple practice with one dimensional data 1

### ISSUE THREAD

**Issue by HidekiInnan** [oreilly-japan/deep-learning-from-scratch#12]
Define input data1 (n x 1) = {P(T-n+1), P(T-n+2), P(T-n+3), .., P(T)}
answer: = 0 if P(T)-d <= P(T+m) <= P(T)+d
             = 1 if P(T+m) > P(T)+d 
             = 2 if P(T+m) < P(T)-d

**Comment by HidekiInnan** [comment]
Practice 1
Sugi: make 10000 random data from USDJPY, 1 minute interval, n=200, m=5, d=5
http://www.histdata.com/download-free-forex-data/?/metatrader/1-minute-bar-quotes
perhaps, use data from 2010 to 2015 to learn, 2016 for testing the performance
Metal: Which optimization algorithm would work best?

**Comment by rsugino** [comment]
What is the "m" and "d"?

**Comment by HidekiInnan** [comment]
the answer is 0 if the price after m minutes is within +- d pips
