### ISSUE TITLE
sys.path.append(os.pardir)がうまく行かず、os.pardirのところにフルパスを指定したところ動きました

### ISSUE THREAD

**Issue by hidehiro98** [oreilly-japan/deep-learning-from-scratch#25]
`sys.path.append(os.pardir)` だと、下記のエラーが出ました。

```
Traceback (most recent call last):
  File "ch05/gradient_check.py", line 5, in <module>
    from dataset.mnist import load_mnist
ModuleNotFoundError: No module named 'dataset'
```

`os.pardir` のところをフルパス (e.g. `Users/user_name/deep-learning-from-scratch`)にしたところ動きました。

環境は
* macOS High Sierra
* Python 3.6.2
* anaconda 1.6.5
です。

**Comment by th3m1s** [comment]
```
import os
import sys
sys.path.append(os.path.abspath('..'))
```
とすれば，自動的にフルパスで展開してくれます．

私の手元の環境は，

- Ubuntu 16.04

- Python 3.5.2
です．

**Comment by Staircing** [comment]
from dataset.mnist import load_mnist
ImportError: No module named 'dataset.mnist'
>>>
