### ISSUE TITLE
3章のMNIST画像の表示にはpillowライブラリが必要なようです

### ISSUE THREAD

**Issue by 3panda** [oreilly-japan/deep-learning-from-scratch#26]
3章のMNIST画像（手書き数字認識のサンプル画像）を表示する部分ですが
mnist_show.pyを実行すると
```
% python mnist_show.py
Traceback (most recent call last):
  File "mnist_show.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```
PILのライブラリが存在しないと言うエラーになります。
こちらですがpillowをインストールで解決致しました。
```
pip3 install pillow
```
どこかに補足など頂けると幸いでございます。

参考にさせていただたURL
https://qiita.com/ukwksk/items/483d1b9e525667b77187

**Comment by KantaSunaga** [comment]
@3panda 

私も引っかかりissueにあがってないか確認したら、同じように困ってる方がいて自分だkではないということに安心しました。笑

どうやら、PIL は開発が中止されてしまい、代わりにそこから枝分かれした、Pillowが使われているようです。

https://note.nkmk.me/python-pillow-basic/
