### ISSUE TITLE
col2im の結果について

### ISSUE THREAD

**Issue by masa-matsu** [oreilly-japan/deep-learning-from-scratch#27]
どうもいつも勉強させていただいております。
deep-learning-from-scratch/common/util.py
の 97行目の col2im でcol から img へ写像するところが代入でなく加算代入になっているようですが正しいでしょうか。

```
for y in range(filter_h):
  y_max = y + stride*out_h
    for x in range(filter_w):
      x_max = x + stride*out_w
      img[:, :, y:y_max:stride, x:x_max:stride] += col[:, :, y, x, :, :] # <- img[:, :, y:y_max:stride, x:x_max:stride] = col[:, :, y, x, :, :] では？ 
```

'+=' では下記の unit test で失敗しましたが、'=' に置き換えると成功しました。

```
    def test_im2col(self):
        input = np.array([[[[ 0,  1,  2], 
                            [ 4,  5,  6], 
                            [ 8,  9, 10]], 
                           [[12, 13, 14], 
                            [16, 17, 18], 
                            [20, 21, 22]]]], dtype=float)

        outExp = np.array([[0, 1, 4, 5, 12, 13, 16, 17],
                           [1, 2, 5, 6, 13, 14, 17, 18],
                           [4, 5, 8, 9, 16, 17, 20, 21],
                           [5, 6, 9,10, 17, 18, 21, 22]], dtype=float)
        
        output = util.im2col(input, 2, 2, 1, 0)
        self.assertEqual(outExp.tolist(), output.tolist())
        x = util.col2im(output, input.shape, 2, 2, 1, 0)
        self.assertEqual(x.tolist(), input.tolist())
```

恐縮ではございますが、ご確認ください。

**Comment by masa-matsu** [comment]
直観的には、Forward 時に参照回数が多いところほど強くなるから、もとのコードのように Backward 時に += が正しいんでしょうね。
Pooling の Backward で、col2im で写像が = だと、フィルタ幅or高より小さいサイズで Stride すると、s最大要素が 0 になることがあり気づきました。
文献などを当たって、理論をしっかり理解したいと思います。
失礼しました。

**Comment by masa-matsu** [comment]
コードに誤りなかったです。こちらの理解不足でした、大変失礼しました。
直観的には、Forward で参照された要素ほど逆伝播で強まると理解しました。

**Comment by dwbaron** [comment]
problem solved by add a weights matrix which count how many times each entry of the col matrix that is added
`def col2im(col, input_shape, filter_h, filter_w, stride=1, pad=0):
    """

    Parameters
    ----------
    col :
    input_shape : 入力データの形状（例：(10, 1, 28, 28)）
    filter_h :
    filter_w
    stride
    pad

    Returns
    -------

    """
    N, C, H, W = input_shape
    out_h = (H + 2*pad - filter_h)//stride + 1
    out_w = (W + 2*pad - filter_w)//stride + 1
    col = col.reshape(N, out_h, out_w, C, filter_h, filter_w).transpose(0, 3, 4, 5, 1, 2)

    img = np.zeros((N, C, H + 2*pad + stride - 1, W + 2*pad + stride - 1))
	weights = np.zeros_like(img)
    for y in range(filter_h):
        y_max = y + stride*out_h
        for x in range(filter_w):
            x_max = x + stride*out_w
            img[:, :, y:y_max:stride, x:x_max:stride] += col[:, :, y, x, :, :]
			weights[:, :, y:y_max:stride, x:x_max:stride] += np.ones_like(img[:, :, y:y_max:stride, x:x_max:stride])

    return img[:, :, pad:H + pad, pad:W + pad] / weights`
