### ISSUE TITLE
P168の6.1.3(SGDの欠点)について

### ISSUE THREAD

**Issue by araiyusuke** [oreilly-japan/deep-learning-from-scratch#34]
P168の関数の勾配をグラフで表示させたのですが、P170 - 図6-3のようなジグザグのグラフではなく、下記のようなグラフになりました。

![2ojjbqb](https://user-images.githubusercontent.com/515809/48527169-988b3600-e8cd-11e8-9967-4d55362f70e2.png)

**Comment by koki0702** [comment]
おそらく、学習率（`lr`）が異なるため、グラフの経路が違うようになったかと思われます。
（本書の例では、SGDの学習率は0.95に設定しています。）

なお、上のグラフの再現は下記のファイルから行えますので、参考にしてください。

https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/ch06/optimizer_compare_naive.py

**Comment by araiyusuke** [comment]
ご返信有難うございます。学習率を高めに設定することでジグザグになりました！
