### ISSUE TITLE
common/gradient.py内のnumerical_gradient関数におけるfloatキャストの必要性

### ISSUE THREAD

**Issue by narugit** [oreilly-japan/deep-learning-from-scratch#42]
[該当箇所](https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/common/gradient.py#L42)につきまして、`tmp_val`をfloat変換しておりますが、[45行目](https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/common/gradient.py#L45)と同様、変換が必要ないと思われます。

ご確認の程、宜しくお願い致します。

**Comment by koki0702** [comment]
ご指摘の通りです。修正しておきます。

ありがとうございます。
