### ISSUE TITLE
8章：学習済みの重みパラメータのファイル名

### ISSUE THREAD

**Issue by segavvy** [oreilly-japan/deep-learning-from-scratch#48]
第13刷のP.243、5行目では

> 学習済みの重みパラメータを`ch08/deep_conv_net_params.pkl`として与えています。

とありますが、実際のファイル名は [ch08/deep_convnet_params.pkl](https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/ch08/deep_convnet_params.pkl) になっています。`conv`と`net`の間の`_`の有無が異なります。

**Comment by koki0702** [comment]
ありがとうございます。
