### ISSUE TITLE
ch3/mnist_show.pyがHTTPErrorとなる

### ISSUE THREAD

**Issue by hone-git** [oreilly-japan/deep-learning-from-scratch#55]
MNISTをダウンロード・表示させるプログラムである，
ch3/mnist_show.pyを実行すると以下のエラーを吐きます．

~~~
urllib.error.HTTPError: HTTP Error 403: Forbidden
~~~

dataset/mnist.py内の関数_downloadを以下に変更することで解決しました．

~~~
def _download(file_name):
    file_path = dataset_dir + "/" + file_name

    if os.path.exists(file_path):
        return

    print("Downloading " + file_name + " ... ")
    headers = {
        "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
        }
    request = urllib.request.Request(url_base+file_name, headers=headers)
    response = urllib.request.urlopen(request).read()
    with open(file_path, mode='wb') as f:
        f.write(response)
    print("Done")
~~~

DL先のサイトhttp://yann.lecun.com/ へのアクセス権限がないことが原因のようです．
「ブラウザからのアクセスだよ」と伝えてあげる必要があります．
私の場合はヘッダーをFirefoxと偽装することで解決しました．

**Comment by hone-git** [comment]
ヘッダーの偽装という方法がまずいのかどうか私にはわかりません（なんかセキュリティ関係で）．
詳しい方がいれば教えてください．

**Comment by koki0702** [comment]
ありがとうございます。
コード修正しました。

https://github.com/oreilly-japan/deep-learning-from-scratch/commit/f549a1886b4c03a252ac7549311e29c1ed78a8a1
