### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by javaboy-github** [oreilly-japan/deep-learning-from-scratch#64]
一応メールで送信しましたが、2週間経っても返信がないようなのでここに書きます。

232ページの8行目、`self.last_layer = SoftmaxWithLoss()`とありますが、そのページの解説や他のコードには、`lastLayer`と表記されています。他の変数がスネークケースで書かれていること、[github](https://github.com/oreilly-japan/deep-learning-from-scratch/blob/f549a1886b4c03a252ac7549311e29c1ed78a8a1/ch07/simple_convnet.py#L59)のコードには全て`last_layer`と表記されていることから、`last_layer`が正しいと思われます。

**Comment by koki0702** [comment]
ご報告ありがとうございます。
ご指摘通り修正します。
